baseURL = "https://GreaterGoodest.github.io"
languageCode = "en-us"
title = "Goodest Blog"
theme = "m10c"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  author = "Ryan Good"
  avatar = "images/greatergoodest.jpg"