baseURL = "https://GreaterGoodest.github.io"
languageCode = "en-us"
title = "Goodest Blog"
theme = "m10c"
disqusShortname = 'https-greatergoodest-github-io'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  author = "Ryan Good"
  avatar = "images/greatergoodest.jpg"
  description = "Blogging about dev, netsec, and malware"
  css = ["css/custom.css"]

  [[params.social]]
  icon = "linkedin"
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/ryanagood/"
  [[params.social]]
  icon = "github"
  name = "GitHub"
  url = "https://github.com/GreaterGoodest/"
  [[params.social]]
  icon = "twitter"
  name = "Twitter"
  url = "https://twitter.com/GreaterGoodest"